CREATE TABLE locations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    latitude DECIMAL(11, 8) NOT NULL,
    longitude DECIMAL (11, 8) NOT NULL,
    user_id INTEGER REFERENCES users(id)  
        ON DELETE SET NULL,
    description TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
)